# Generated by Django 2.1 on 2018-08-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('link', models.URLField(max_length=250)),
                ('image', models.ImageField(max_length=45, upload_to='uploads/partners/')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('email', models.EmailField(default='someone@angoapp.com', max_length=254)),
                ('photo', models.ImageField(max_length=45, upload_to='uploads/profiles/')),
                ('role', models.CharField(blank=True, max_length=45)),
                ('administrator', models.BooleanField(default=False)),
                ('bio', models.TextField(blank=True, max_length=800)),
                ('linkedin', models.URLField(default='https://linkedin/company/angoapp')),
                ('github', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Persons',
            },
        ),
    ]
